"""The M4 reports, rendered from ``artifacts/m4/audit.json`` and ``configs/taxonomy.yaml`` alone.

Everything here is a pure function of the audit and the taxonomy, so the committed reports can be
checked against the committed files without any data.
"""

from __future__ import annotations

import os
from collections.abc import Callable, Sequence
from pathlib import Path

from openinspect.taxonomy.audit import ClassRow, M4Audit, Spread
from openinspect.taxonomy.config import COMPARABLE, Taxonomy
from openinspect.taxonomy.quality import CHECKS, SIGNALS

DASH = "n/a"
SOURCE_LINE = (
    "Generated by `openinspect taxonomy audit` from `artifacts/m4/audit.json` and "
    "`configs/taxonomy.yaml` (re-render with `openinspect taxonomy report`)."
)
IMMUTABLE = (
    "Original labels are never changed: every box keeps the label its source gave it, and the "
    "normalized label is added next to it (`artifacts/m4/taxonomy-map.parquet`). A mapping rests "
    "on the source's paper and documentation and on sampled boxes, not on the label's name; the "
    "definitions and the reasoning are in [docs/TAXONOMY.md](../../docs/TAXONOMY.md)."
)
STATUS_MEANING = {
    "EXACT": "the source's definition says what the normalized class says",
    "COMPATIBLE": "the same concept, with a documented difference in scope or wording",
    "AMBIGUOUS": "a candidate relation exists but the evidence does not settle it: not merged",
    "SOURCE_SPECIFIC": "no counterpart in another source: kept as its own class",
    "REJECTED": "not a defect class (a placeholder): never used",
}
REPORTS = ("taxonomy-mapping.md", "class-overlap.md", "label-quality.md")


def _int(value: int | None) -> str:
    return DASH if value is None else f"{value:,}"


def _pct(part: int, whole: int) -> str:
    return DASH if whole == 0 else f"{100 * part / whole:.1f}%"


def _table(headers: Sequence[str], rows: Sequence[Sequence[str]]) -> list[str]:
    lines = ["| " + " | ".join(headers) + " |", "|" + "---|" * len(headers)]
    lines.extend("| " + " | ".join(row) + " |" for row in rows)
    return lines


def _code(value: str) -> str:
    return f"`{value}`"


def _cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def _header(title: str, audit: M4Audit) -> list[str]:
    commit = audit.run.code_commit
    code = (
        DASH
        if commit is None
        else f"`{commit[:12]}`" + (" with uncommitted changes" if audit.run.code_dirty else "")
    )
    return [
        f"# {title}",
        "",
        f"{SOURCE_LINE} Code: {code}; taxonomy SHA-256 `{audit.run.taxonomy_sha256[:12]}`.",
        "",
        IMMUTABLE,
        "",
    ]


def _sources(audit: M4Audit) -> list[str]:
    return [s.source for s in audit.sources]


def _reach_cell(row: ClassRow, source: str) -> str:
    reached = [r for r in row.reached_by if r.source == source]
    if reached:
        return ", ".join(f"{r.status} {_code(r.original_label)}" for r in reached)
    candidates = [r for r in row.candidate_of if r.source == source]
    if candidates:
        return ", ".join(f"(candidate of AMBIGUOUS {_code(r.original_label)})" for r in candidates)
    return "-"


def _comparable_sources(row: ClassRow) -> list[str]:
    return sorted({r.source for r in row.reached_by if r.status in COMPARABLE})


def _spread(value: Spread | None, scale: float = 1.0, digits: int = 0, unit: str = "") -> str:
    if value is None:
        return DASH
    parts = (value.p10 * scale, value.median * scale, value.p90 * scale)
    return " / ".join(f"{p:,.{digits}f}{unit}" for p in parts)


# ------------------------------------------------------------------- taxonomy mapping


def taxonomy_mapping(audit: M4Audit, taxonomy: Taxonomy) -> str:
    lines = _header("M4 taxonomy mapping", audit)
    lines += ["## Statuses", ""]
    lines += _table(["status", "meaning"], [[s, m] for s, m in STATUS_MEANING.items()])
    lines += [
        "",
        "A normalized class is a **benchmark class** when every source reaches it with an EXACT or "
        "COMPATIBLE mapping: only those are compared across sources. Benchmark classes: "
        + ", ".join(_code(c) for c in audit.benchmark_classes)
        + ".",
        "",
        "## Normalized classes",
        "",
        f"Level 0: `{taxonomy.hierarchy.level_0}`. Level 1 families follow the grouping of the "
        "only source paper that publishes one.",
        "",
    ]
    lines += _table(
        ["family", "meaning"], [[_code(f), m] for f, m in taxonomy.hierarchy.families.items()]
    )
    lines.append("")
    lines += _table(
        ["normalized class", "family", "definition", "sources reaching it (EXACT or COMPATIBLE)"],
        [
            [
                _code(row.normalized_label),
                _code(row.family),
                _cell(taxonomy.classes[row.normalized_label].definition),
                str(len(_comparable_sources(row))),
            ]
            for row in audit.classes
        ],
    )
    for source in sorted(taxonomy.mappings):
        rows = [r for r in audit.labels if r.source == source]
        lines += [
            "",
            f"## `{source}`",
            "",
            f"Definitions quoted from: {_cell(taxonomy.citations[source])}.",
            "",
        ]
        lines += _table(
            ["original label", "boxes", "images", "normalized label", "status", "evidence"],
            [
                [
                    _code(r.original_label) + ("" if r.declared else " (not declared)"),
                    _int(r.boxes),
                    _int(r.images),
                    _code(r.normalized_label) if r.normalized_label else "-",
                    r.status,
                    _cell(taxonomy.mapping(source, r.original_label).evidence),
                ]
                for r in rows
            ],
        )
    sources = sorted(taxonomy.mappings)
    lines += [
        "",
        "## Reverse mapping",
        "",
        "Every normalized label leads back to the original labels it came from, so the mapping can "
        "be undone per source:",
        "",
    ]
    lines += _table(
        ["normalized class", *sources],
        [
            [
                _code(name),
                *(
                    ", ".join(_code(label) for label in taxonomy.original_labels(source, name))
                    or "-"
                    for source in sources
                ),
            ]
            for name in taxonomy.classes
        ],
    )
    if taxonomy.considered_merges:
        lines += ["", "## Candidate merges that were examined and not made", ""]
        lines += _table(
            ["labels", "decision", "reason"],
            [
                [", ".join(_code(label) for label in m.labels), m.decision, _cell(m.reason)]
                for m in taxonomy.considered_merges
            ],
        )
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------- class overlap


def _answer(audit: M4Audit) -> list[str]:
    n_sources = len(audit.sources)
    benchmark = [r for r in audit.classes if r.benchmark]
    compatible = [
        f"{_code(r.source)} {_code(r.original_label)} to {_code(row.normalized_label)}"
        for row in benchmark
        for r in row.reached_by
        if r.status == "COMPATIBLE"
    ]
    reaches = sum(len([r for r in row.reached_by if r.status in COMPARABLE]) for row in benchmark)
    partial = [
        row for row in audit.classes if not row.benchmark and len(_comparable_sources(row)) >= 2
    ]
    text = (
        f"**Answer.** {len(benchmark)} classes can be compared across all {n_sources} independent "
        "sources without silently changing their meaning: "
        + ", ".join(_code(r.normalized_label) for r in benchmark)
        + f" (an EXACT or COMPATIBLE mapping in every source). Of the {reaches} mappings behind "
        "them, "
        + (
            f"{len(compatible)} are COMPATIBLE rather than EXACT ({'; '.join(compatible)}); their "
            "differences in scope are part of the evidence in "
            "[taxonomy-mapping.md](taxonomy-mapping.md)."
            if compatible
            else "all are EXACT."
        )
    )
    lines = [text, ""]
    if partial:
        lines += [
            "Shared by some sources but not all, so outside the cross-source benchmark: "
            + "; ".join(
                f"{_code(row.normalized_label)} ({', '.join(_code(s) for s in _comparable_sources(row))})"
                for row in partial
            )
            + ".",
            "",
        ]
    lines += [
        "Every other class is source-specific or ambiguous and keeps its own name; no label was "
        "merged to enlarge the overlap.",
        "",
    ]
    return lines


def class_overlap(audit: M4Audit, taxonomy: Taxonomy) -> str:
    lines = _header("M4 class overlap", audit)
    lines += _answer(audit)
    sources = _sources(audit)
    lines += ["## Which source reaches which class", ""]
    lines += _table(
        ["normalized class", "family", *sources, "benchmark"],
        [
            [
                _code(row.normalized_label),
                _code(row.family),
                *(_reach_cell(row, s) for s in sources),
                "yes"
                if row.benchmark
                else f"no ({len(_comparable_sources(row))} of {len(sources)} sources)",
            ]
            for row in audit.classes
        ],
    )
    lines += [
        "",
        "## What a cross-source release keeps of each source",
        "",
        "An image whose boxes all map onto benchmark classes is eligible. An image with any box of "
        "another class is excluded as a whole (SPEC 7.4): dropping only that box would turn a real "
        "defect into background. An image without boxes is a negative.",
        "",
    ]
    lines += _table(
        [
            "source",
            "acquisition",
            "images",
            "negatives",
            "eligible images",
            "excluded images",
            "boxes in eligible images",
            "benchmark boxes lost with excluded images",
        ],
        [
            [
                _code(s.source),
                s.acquisition_id or DASH,
                _int(s.images),
                _int(s.negatives),
                f"{_int(s.eligible_images)} ({_pct(s.eligible_images, s.images)})",
                f"{_int(s.excluded_images)} ({_pct(s.excluded_images, s.images)})",
                _int(s.eligible_boxes),
                _int(s.benchmark_boxes_in_excluded),
            ]
            for s in audit.sources
        ],
    )
    crops_only = [
        s for s in audit.sources if s.eligible_images == 0 and s.benchmark_boxes_in_excluded
    ]
    if crops_only:
        lines += [""] + [
            f"`{s.source}`: no whole image is eligible, because every image holds a box of another "
            f"class; its {_int(s.benchmark_boxes_in_excluded)} benchmark-class boxes can enter a "
            "release only as crops that contain no box of another class (M5, decision D7)."
            for s in crops_only
        ]
    lines += ["", "Excluded images by the label that excludes them (an image can count twice):", ""]
    lines += _table(
        ["source", "label", "excluded images"],
        [
            [_code(s.source), _code(label), _int(n)]
            for s in audit.sources
            for label, n in s.excluded_by.items()
        ],
    )
    lines += ["", "Eligible images by the source's own split:", ""]
    lines += _table(
        ["source", "eligible images per original split"],
        [
            [
                _code(s.source),
                ", ".join(f"{k} {_int(v)}" for k, v in s.eligible_by_split.items()) or "-",
            ]
            for s in audit.sources
        ],
    )
    lines += ["", "## Benchmark classes in the eligible images", ""]
    geometry = {(g.normalized_label, g.source): g for g in audit.geometry}
    lines += _table(
        ["class", *(f"{s} boxes (images)" for s in sources), "boxes"],
        [
            [
                _code(name),
                *(
                    f"{_int(geometry[(name, s)].boxes)} ({_int(geometry[(name, s)].images)})"
                    if (name, s) in geometry
                    else DASH
                    for s in sources
                ),
                _int(sum(geometry[(name, s)].boxes for s in sources if (name, s) in geometry)),
            ]
            for name in audit.benchmark_classes
        ],
    )
    lines += [
        "",
        "## Are the boxes comparable in size?",
        "",
        "Same class, same meaning, but not the same picture: box size relative to the image "
        "(p10 / median / p90) and in pixels. Large scans make a defect a small share of the image; "
        "release assembly (M5) cuts ROI crops around the boxes of such sources (decision D7) so "
        "that a defect fills a share of the image comparable to the AOI patches.",
        "",
    ]
    lines += _table(
        [
            "class",
            "source",
            "boxes",
            "box area / image area",
            "box long side px",
            "image long side px",
        ],
        [
            [
                _code(g.normalized_label),
                _code(g.source),
                _int(g.boxes),
                _spread(g.relative_area, 100, 2, "%"),
                _spread(g.long_side_px),
                _spread(g.image_long_side_px),
            ]
            for g in audit.geometry
        ],
    )
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------- label quality


def label_quality(audit: M4Audit, taxonomy: Taxonomy) -> str:
    lines = _header("M4 label quality", audit)
    lines += [
        audit.human_validation.statement + " The near-duplicate check below uses the M3 pairs.",
        "",
        "No label, box or image was changed or dropped. Each finding is one row of "
        "`artifacts/m4/review-required.csv` with status `REVIEW_REQUIRED` and empty "
        f"`human_decision` and `human_notes` columns: {_int(audit.review_rows)} rows. A finding "
        "asks a person to look; it is not an error count.",
        "",
        "## Rules",
        "",
    ]
    rules = audit.rules
    lines += _table(
        ["signal", "check", "rule"],
        [[_code(signal), check, rule] for signal, (check, rule) in SIGNALS.items()],
    )
    lines += [
        "",
        f"Values: `min_box_side_px` {rules.min_box_side_px:g}, `max_aspect_ratio` "
        f"{rules.max_aspect_ratio:g}, `same_box_iou` {rules.same_box_iou:g}, `size_outlier_z` "
        f"{rules.size_outlier_z:g}; M3 near level cosine {audit.run.near_threshold:g} and pHash "
        f"distance at most {audit.run.phash_max}; ingest flags taken as informational: "
        + (", ".join(_code(f) for f in rules.informational_flags) or "none")
        + ".",
        "",
        "## Findings",
        "",
    ]
    sources = _sources(audit)
    counts = {(c.signal, c.source): c for c in audit.signals}
    rows: list[list[str]] = []
    for signal in SIGNALS:
        if not any((signal, s) in counts for s in sources):
            rows.append([_code(signal), SIGNALS[signal][0], *("0" for _ in sources), "0"])
            continue
        cells = [
            _int(counts[(signal, s)].findings) if (signal, s) in counts else "0" for s in sources
        ]
        total = sum(counts[(signal, s)].findings for s in sources if (signal, s) in counts)
        rows.append([_code(signal), SIGNALS[signal][0], *cells, _int(total)])
    lines += _table(["signal", "check", *sources, "total"], rows)
    by_check = {
        check: sum(c.findings for c in audit.signals if c.check == check) for check in CHECKS
    }
    lines += [
        "",
        "Per check: " + ", ".join(f"{check} {_int(n)}" for check, n in by_check.items()) + ".",
        "",
        "## Near-duplicate pairs and their labels",
        "",
        "Descriptive: how often the machine-detected near-duplicate pairs of M3 (an "
        "embedding-based similarity finding, not proof of shared content) carry different "
        "normalized label sets. Only strict pairs (also within the pHash distance, or identical "
        "bytes) with different label sets become findings; two images of neighbouring regions "
        "can legitimately show different defects.",
        "",
    ]
    lines += _table(
        ["scope", "near pairs", "with different labels", "strict pairs", "with different labels"],
        [
            [
                _code(a.scope),
                _int(a.near_pairs),
                f"{_int(a.near_pairs_differing)} ({_pct(a.near_pairs_differing, a.near_pairs)})",
                _int(a.strict_pairs),
                f"{_int(a.strict_pairs_differing)} "
                f"({_pct(a.strict_pairs_differing, a.strict_pairs)})",
            ]
            for a in audit.agreement
        ],
    )
    lines += ["", "## Examples", "", "The first findings of each signal in queue order:", ""]
    lines += _table(
        ["signal", "source", "image", "box", "label", "related image", "measure", "detail"],
        [
            [
                _code(e.signal),
                _code(e.source_id),
                _code(e.image_id) if e.image_id else "-",
                "-" if e.ann_index is None else str(e.ann_index),
                _cell(e.original_label) or "-",
                _code(e.related_image_id) if e.related_image_id else "-",
                DASH if e.measure is None else f"{e.measure:g}",
                _cell(e.detail),
            ]
            for e in audit.examples
        ],
    )
    lines += [
        "",
        "## Not checked in M4",
        "",
        "Neighbour labels of box-crop embeddings, classifier and detector disagreement and "
        "embedding outliers (SPEC 7.5, S1 to S4) need box-level embeddings or trained models; they "
        "come after the first trained models (M7). Until then the queue holds rule-based findings "
        "only, and no finding has been reviewed.",
        "",
    ]
    return "\n".join(lines) + "\n"


RENDERERS: dict[str, Callable[[M4Audit, Taxonomy], str]] = {
    "taxonomy-mapping.md": taxonomy_mapping,
    "class-overlap.md": class_overlap,
    "label-quality.md": label_quality,
}


def render_reports(audit: M4Audit, taxonomy: Taxonomy) -> dict[str, str]:
    return {name: render(audit, taxonomy) for name, render in RENDERERS.items()}


def write_reports(folder: Path, audit: M4Audit, taxonomy: Taxonomy) -> list[Path]:
    written: list[Path] = []
    for name, text in sorted(render_reports(audit, taxonomy).items()):
        path = folder / name
        path.parent.mkdir(parents=True, exist_ok=True)
        temporary = path.with_name(f"{path.name}.{os.getpid()}.tmp")
        temporary.write_bytes(text.encode("utf-8"))
        os.replace(temporary, path)
        written.append(path)
    return written
