"""The M3 reports: five Markdown files and their SVG figures, rendered from the audit alone (M3J).

Everything here is a pure function of :class:`~openinspect.dedup.audit_models.Audit`, so the
committed reports can be checked against the committed ``artifacts/m3/audit.json`` without any
data. Sentences state measurements; interpretation that needs judgement is left to the reader and
to the milestone report.
"""

from __future__ import annotations

import os
import re
from collections.abc import Callable, Sequence
from pathlib import Path

from openinspect.dedup.audit_models import (
    Audit,
    Interval,
    LevelResult,
    Top1Stats,
)
from openinspect.dedup.leakage import KeyOverlap, PermutationBaseline, SourceLeakage
from openinspect.dedup.metrics import PartitionAgreement, Quantiles
from openinspect.dedup.svg import Bars, Marker, Series, bar_chart, line_chart
from openinspect.dedup.thresholds import CATEGORIES

DASH = "n/a"
PROTOCOL = "[docs/M3_PROTOCOL.md](../../docs/M3_PROTOCOL.md)"
AMENDMENT = "[docs/M3_PROTOCOL_AMENDMENT.md](../../docs/M3_PROTOCOL_AMENDMENT.md)"
SOURCE_LINE = (
    "Generated by `openinspect dedup analyze` from `artifacts/m3/audit.json` "
    "(re-render with `openinspect dedup report`)."
)
VOCABULARY = (
    "A *visual similarity group* is a connected component of image pairs whose embedding cosine "
    "reaches a threshold: evidence of a potential leakage group, not proof that two images show the "
    "same physical board. No image was deleted, excluded or re-labelled."
)
REPORTS = (
    "similarity-summary.md",
    "threshold-calibration.md",
    "split-leakage.md",
    "source-comparison.md",
    "performance.md",
)


# ------------------------------------------------------------------------------ format


def _int(value: int | None) -> str:
    return DASH if value is None else f"{value:,}"


def _f(value: float | None, digits: int = 3) -> str:
    return DASH if value is None else f"{value:.{digits}f}"


def _pct(part: int | float | None, whole: int | float | None) -> str:
    if part is None or not whole:
        return DASH
    return f"{100 * part / whole:.1f}%"


def _share(value: float | None) -> str:
    return DASH if value is None else f"{100 * value:.1f}%"


def _ci(interval: Interval | None) -> str:
    return DASH if interval is None else f"[{interval.low:.3f}, {interval.high:.3f}]"


def _q(q: Quantiles | None, digits: int = 3) -> str:
    if q is None:
        return DASH
    return f"{q.median:.{digits}f} ({q.p05:.{digits}f} to {q.p95:.{digits}f})"


def _p(value: float, n: int) -> str:
    return f"< {1 / n:.3f}" if value == 0 else f"{value:.3f}"


def _p_text(value: float, n: int) -> str:
    return f"< {1 / n:.3f}" if value == 0 else f"= {value:.3f}"


def _table(headers: Sequence[str], rows: Sequence[Sequence[str]]) -> list[str]:
    lines = ["| " + " | ".join(headers) + " |", "|" + "---|" * len(headers)]
    lines.extend("| " + " | ".join(row) + " |" for row in rows)
    return lines


def slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-") or "x"


def _header(title: str, audit: Audit) -> list[str]:
    commit = audit.run.code_commit
    code = (
        DASH
        if commit is None
        else f"`{commit[:12]}`" + (" with uncommitted changes" if audit.run.code_dirty else "")
    )
    return [
        f"# {title}",
        "",
        f"{SOURCE_LINE} Rules: {PROTOCOL} (frozen before any leakage number was computed) and "
        f"{AMENDMENT}. Code: {code}; seed {audit.run.seed}.",
        "",
        VOCABULARY,
        "",
    ]


def _sources(audit: Audit) -> list[str]:
    return [s.source for s in audit.run.sources]


def _level(audit: Audit, name: str) -> LevelResult | None:
    return next((level for level in audit.levels if level.level == name), None)


def primary_level(audit: Audit, source: str) -> str:
    """The chaining rule (protocol section 8): ``near`` if the source chains at ``family``."""
    family = _level(audit, "family")
    return "near" if family is not None and source in family.chained_sources else "family"


# ------------------------------------------------------------------------------ figures


def _figure(name: str, alt: str) -> str:
    return f"![{alt}](figures/{name})"


def figures(audit: Audit) -> dict[str, str]:
    t = audit.thresholds
    marks = [Marker(t.review, "review"), Marker(t.family, "family"), Marker(t.near, "near")]
    if t.review == t.family:
        marks = [Marker(t.family, "review = family"), Marker(t.near, "near")]
    out: dict[str, str] = {}
    cdfs = [Series(s.source, s.cdf) for s in audit.top1 if s.cdf]
    if cdfs:
        low = min((s.within_source.p05 for s in audit.top1 if s.within_source), default=0.0)
        x0 = max(0.0, int(low * 10) / 10)
        out["top1-cdf.svg"] = line_chart(
            "Most similar other image of the same source",
            "cosine similarity",
            "share of images at or below",
            [Series(s.name, [p for p in s.points if p[0] >= x0]) for s in cdfs],
            x_range=(x0, 1.0),
            y_range=(0.0, 1.0),
            markers=marks,
        )
    pools = [p for p in audit.pools if p.roc]
    if pools:
        out["roc.svg"] = line_chart(
            "ROC against group labels",
            "false positive rate",
            "true positive rate (recall)",
            [Series(f"{p.source} {p.pool}", p.roc) for p in pools]
            + [Series("chance", [(0.0, 0.0), (1.0, 1.0)], color="#bbbbbb", dashed=True)],
            x_range=(0.0, 1.0),
            y_range=(0.0, 1.0),
        )
        out["pr.svg"] = line_chart(
            "Precision and recall against group labels",
            "recall",
            "precision",
            [Series(f"{p.source} {p.pool}", p.pr) for p in pools],
            x_range=(0.0, 1.0),
            y_range=(0.0, 1.0),
        )
    for pool in audit.pools:
        if not pool.histogram:
            continue
        x0 = max(-1.0, int(min(c for c, _, _ in pool.histogram) * 10) / 10 - 0.1)
        top = max(max(pos, neg) for _, pos, neg in pool.histogram)
        out[f"histogram-{slug(pool.source)}-{slug(pool.pool)}.svg"] = line_chart(
            f"{pool.source}: cosine of positive and negative pairs ({pool.pool})",
            "cosine similarity (0.01 bins)",
            "share of the class's pairs",
            [
                Series("positive (same group)", [(c, pos) for c, pos, _ in pool.histogram]),
                Series("negative (other group)", [(c, neg) for c, _, neg in pool.histogram]),
            ],
            x_range=(x0, 1.0),
            y_range=(0.0, max(top * 1.1, 0.01)),
            markers=marks,
        )
    if audit.synthetic is not None and audit.synthetic.by_transform:
        rows = audit.synthetic.by_transform
        out["synthetic.svg"] = bar_chart(
            "Synthetic copies at or above the near threshold",
            "transform",
            "share of copies",
            [r.transform.replace("_", " ") for r in rows],
            [Bars("share >= near", [r.share_near for r in rows])],
            y_max=1.0,
            width=760,
        )
    crossing = _crossing_bars(audit)
    if crossing is not None:
        out["cross-split.svg"] = crossing
    percolation = _percolation_chart(audit, marks)
    if percolation is not None:
        out["percolation.svg"] = percolation
    return out


def _crossing_bars(audit: Audit) -> str | None:
    categories: list[str] = []
    observed: list[float] = []
    expected: list[float] = []
    for level in audit.levels:
        for leak in level.leakage:
            baseline = level.permutation.get(leak.source)
            if leak.has_splits and baseline is not None:
                categories.append(f"{leak.source} {level.level}")
                observed.append(float(leak.groups_crossing_any))
                expected.append(round(baseline.null_mean, 1))
    if not categories:
        return None
    return bar_chart(
        "Similarity groups that cross a split boundary",
        "source and level",
        "groups",
        categories,
        [Bars("official split", observed), Bars("random splits (mean)", expected)],
        width=760,
    )


def _percolation_chart(audit: Audit, marks: list[Marker]) -> str | None:
    series: list[Series] = []
    sizes = {s.source: s.images for s in audit.run.sources}
    lows: list[float] = []
    for source in _sources(audit):
        rows = sorted(
            (r for r in audit.percolation if r.source == source), key=lambda r: r.threshold
        )
        if rows and sizes.get(source):
            series.append(Series(source, [(r.threshold, r.largest / sizes[source]) for r in rows]))
            lows.append(rows[0].threshold)
    if not series:
        return None
    return line_chart(
        "Largest similarity group as the threshold drops",
        "cosine threshold",
        "largest group / images of the source",
        series,
        x_range=(int(min(lows) * 100) / 100, 1.0),
        y_range=(0.0, 1.0),
        markers=marks,
    )


# -------------------------------------------------------------------- similarity summary


def similarity_summary(audit: Audit) -> str:
    run, t = audit.run, audit.thresholds
    lines = _header("M3 similarity summary", audit)
    lines += ["## Run", ""]
    lines += _table(
        ["item", "value"],
        [
            [
                "model",
                f"`{run.model_id}` at revision `{run.revision[:12]}` (weights SHA-256 "
                f"`{run.weights_sha256[:12]}…`), {run.dim} dimensions",
            ],
            ["preprocessing, backend", f"`{run.preprocessing_version}`, `{run.backend}`"],
            ["perceptual hash", f"`{run.phash_version}` (64-bit DCT hash); dHash from ingest"],
            [
                "images",
                f"{run.images:,}; failed to read or decode: {len(run.failures)} "
                f"(undecodable at ingest: {run.skipped_at_ingest})",
            ],
        ],
    )
    lines += ["", "## Inputs", ""]
    lines += _table(
        [
            "source",
            "images",
            "annotations",
            "with features",
            "failed",
            "original splits",
            "group key",
        ],
        [
            [
                f"`{s.source}`",
                _int(s.images),
                _int(s.annotations),
                _int(s.embedded),
                _int(s.failed),
                " / ".join(f"{k} {v:,}" for k, v in s.splits.items()),
                s.group_key or "none",
            ]
            for s in run.sources
        ],
    )
    lines += ["", "## Thresholds (protocol section 6, applied mechanically)", ""]
    lines += _table(
        ["level", "value", "category it opens"],
        [
            ["near", _f(t.near, 4), "`NEAR_DUPLICATE` at or above"],
            ["family", _f(t.family, 4), "`SAME_FAMILY_OR_SCENE` from here up to near"],
            ["review", _f(t.review, 4), "`REVIEW_REQUIRED` from here up to family"],
            [
                "pHash candidate",
                f"<= {t.phash_candidate} bits",
                "`REVIEW_REQUIRED` when the hash is this close but the cosine is under review",
            ],
        ],
    )
    fallbacks = [f"`{p.source}` {p.pool}: {p.fallback}" for p in t.from_pools if p.fallback]
    lines += [""]
    if fallbacks:
        lines += ["Fallbacks the rule applied (rule 5):", ""]
        lines += [f"- {f}" for f in fallbacks]
        lines += [""]
    if t.review == t.family:
        lines += [
            "The review and family thresholds coincide, so no pair is `REVIEW_REQUIRED` by cosine "
            "alone; that category holds only pairs whose pHash is close while the cosine is not.",
            "",
        ]
    lines += [
        "How each value was obtained: [threshold-calibration.md](threshold-calibration.md).",
        "",
        "## Exact duplicates",
        "",
        f"Identical SHA-256: {audit.hash_audit.sha256_equal_pairs:,} pairs in "
        f"{audit.hash_audit.sha256_equal_groups:,} groups over all {run.images:,} images, "
        f"{audit.cross_source.sha256_equal_pairs:,} of them across sources.",
        "",
        "## Candidate pairs by suggested category",
        "",
        "Counts of image pairs; in brackets the pairs whose two images sit in different official "
        "splits of the same source.",
        "",
    ]
    scopes = sorted({c.scope for c in audit.categories}, key=lambda s: (s == "across", s))
    rows = []
    for scope in scopes:
        cells = [f"`{scope}`"]
        for category in CATEGORIES:
            count = next(
                (c for c in audit.categories if c.scope == scope and c.category == category), None
            )
            cells.append(DASH if count is None else f"{count.pairs:,} ({count.cross_split:,})")
        rows.append(cells)
    lines += _table(["scope", *(f"`{c}`" for c in CATEGORIES)], rows)
    lines += ["", "## Most similar other image of the same source (no threshold)", ""]
    lines += _table(
        [
            "source",
            "images",
            "top-1 cosine: median (p05 to p95)",
            "max",
            ">= review",
            ">= family",
            ">= near",
            "nearest image of all is in another source (>= family)",
        ],
        [
            [
                f"`{s.source}`",
                _int(s.images),
                _q(s.within_source),
                _f(s.within_source.maximum if s.within_source else None),
                _share(s.share_review),
                _share(s.share_family),
                _share(s.share_near),
                f"{s.nearest_is_other_source:,} ({s.other_source_family:,})",
            ]
            for s in audit.top1
        ],
    )
    keyed = [s for s in audit.top1 if s.top1_same_group is not None]
    if keyed:
        lines += ["", "Does the most similar image share the source's own key?", ""]
        lines += _table(
            ["source", "shares the group key", "chance", "shares the subgroup key", "chance"],
            [_key_row(s) for s in keyed],
        )
    lines += ["", _figure("top1-cdf.svg", "Top-1 cosine per source"), ""]
    lines += _hash_section(audit)
    lines += _cross_source_section(audit)
    return "\n".join(lines) + "\n"


def _key_row(s: Top1Stats) -> list[str]:
    return [
        f"`{s.source}`",
        _share(s.top1_same_group),
        _share(s.chance_same_group),
        _share(s.top1_same_subgroup),
        _share(s.chance_same_subgroup),
    ]


def _hash_section(audit: Audit) -> list[str]:
    h = audit.hash_audit
    lines = [
        "## Hash audit",
        "",
        f"Pairs within a Hamming distance, at the PCB-IND authors' distance ({h.authors_distance} "
        f"bits) and at the calibrated candidate distance ({h.candidate_distance} bits).",
        "",
    ]
    lines += _table(
        [
            "hash",
            "bits",
            "scope",
            "pairs",
            "same subgroup",
            "same group, other subgroup",
            "other group",
            "cross-split",
        ],
        [
            [
                s.algorithm,
                str(s.distance),
                f"`{s.scope}`",
                _int(s.pairs),
                _int(s.same_subgroup),
                _int(s.same_group_other_subgroup),
                _int(s.other_group),
                _int(s.cross_split),
            ]
            for s in h.scopes
        ],
    )
    lines += [
        "",
        "Share of pHash-candidate pairs whose two images also share a family-level similarity "
        "group: "
        + "; ".join(f"`{k}` {_share(v)}" for k, v in sorted(h.phash_in_family_group.items()))
        + ".",
        "",
    ]
    return lines


def _cross_source_section(audit: Audit) -> list[str]:
    c = audit.cross_source
    lines = ["## Across sources", ""]
    lines += _table(
        ["level", "sources", "pairs", "images of the first", "images of the second"],
        [
            [
                e.level,
                f"`{e.source_a}` / `{e.source_b}`",
                _int(e.pairs),
                _int(e.images_a),
                _int(e.images_b),
            ]
            for e in c.edges
        ],
    )
    if c.top_pairs:
        lines += ["", "Most similar pairs across sources:", ""]
        lines += _table(
            ["cosine", "image", "image"],
            [[_f(s, 4), f"`{a}`", f"`{b}`"] for a, b, s in c.top_pairs],
        )
    lines += [""]
    return lines


# --------------------------------------------------------------------- calibration


def threshold_calibration(audit: Audit) -> str:
    t = audit.thresholds
    lines = _header("M3 threshold calibration", audit)
    lines += [
        "The rule of protocol section 6 is applied by `openinspect.dedup.thresholds.select_thresholds`; "
        "nothing below was tuned by hand.",
        "",
        "Pair labels come from each source's own grouping key and are noisy in both directions (two "
        "images of one group can look unlike; two groups can carry one design), so every number "
        "here is *group-label agreement*, not accuracy. Every pair of a source is counted, so "
        "precision is the precision over the whole population of pairs.",
        "",
        "## Pools",
        "",
    ]
    lines += _table(
        [
            "source",
            "pool",
            "used by the rule",
            "images",
            "positive pairs",
            "negative pairs",
            "negatives per positive",
            "ROC AUC [95% CI]",
            "average precision [95% CI]",
        ],
        [
            [
                f"`{p.source}`",
                p.pool,
                "yes" if p.used_in_rule else "no (informational)",
                _int(p.images),
                _int(p.positives),
                _int(p.negatives),
                _f(p.negatives / p.positives, 0) if p.positives else DASH,
                f"{_f(p.auc)} {_ci(p.auc_ci)}",
                f"{_f(p.average_precision)} {_ci(p.average_precision_ci)}",
            ]
            for p in audit.pools
        ],
    )
    lines += ["", "## Operating points", ""]
    rows = []
    for p in audit.pools:
        for name in ("review", "family", "near"):
            point = p.at_thresholds.get(name)
            if point is None:
                continue
            ci = ""
            if name == "family":
                ci = f" {_ci(p.precision_ci_at_family)}"
            rows.append(
                [
                    f"`{p.source}` {p.pool}",
                    name,
                    _f(point.threshold, 4),
                    _f(point.precision) + ci,
                    _f(point.recall)
                    + (f" {_ci(p.recall_ci_at_family)}" if name == "family" else ""),
                    _f(point.f1),
                    _f(point.fpr, 5),
                    _int(point.pairs_above),
                ]
            )
    lines += _table(
        [
            "pool",
            "level",
            "cosine",
            "precision [95% CI]",
            "recall [95% CI]",
            "F1",
            "false positive rate",
            "pairs at or above",
        ],
        rows,
    )
    lines += ["", "## How the rule produced the thresholds", ""]
    lines += _table(
        [
            "source",
            "pool",
            "used by the rule",
            "cosine for precision 0.50",
            "cosine for precision 0.90",
            "F1-optimal cosine",
            "used: review / family",
            "fallback",
        ],
        [
            [
                f"`{p.source}`",
                p.pool,
                "yes" if p.used_in_rule else "no",
                _f(p.precision_050, 4) if p.precision_050 is not None else "never reached",
                _f(p.precision_090, 4) if p.precision_090 is not None else "never reached",
                _f(p.f1_optimal, 4),
                f"{_f(p.review, 4)} / {_f(p.family, 4)}",
                p.fallback or DASH,
            ]
            for p in t.from_pools
        ],
    )
    ruled = [p for p in t.from_pools if p.used_in_rule and p.family is not None]
    lines += [
        "",
        "Precision is judged from the most similar pairs downwards and only where at least 50 pairs "
        "sit at or above the cosine; the search stops at the first such cosine that misses the target.",
        "",
        "1. **family** = the largest value used over the pools of the rule = "
        + " vs ".join(f"{_f(p.family, 4)} (`{p.source}`)" for p in ruled)
        + f" = **{_f(t.family, 4)}**.",
        "2. **review** = min(family, the largest review value used over those pools) = "
        f"**{_f(t.review, 4)}**.",
    ]
    if t.from_synthetic:
        lowest = min(t.from_synthetic, key=lambda s: s.near)
        lines += [
            "3. **near** = max(family, the lowest over the sources of the cosine that keeps 95% of "
            "the synthetic near-duplicates): "
            + ", ".join(
                f"`{s.source}` {_f(s.near, 4)} (n = {s.n_near:,})" for s in t.from_synthetic
            )
            + f"; lowest {_f(lowest.near, 4)}; near = **{_f(t.near, 4)}**.",
            "4. **pHash candidate** = the largest over the sources of the distance that covers 95% of "
            "the photometric copies: "
            + ", ".join(
                f"`{s.source}` {s.phash} bits (n = {s.n_photometric:,})" for s in t.from_synthetic
            )
            + f"; capped at 12; value **{t.phash_candidate} bits**.",
        ]
    lines += [f"- {note}" for note in t.notes]
    lines += ["", "## Hash distances as a baseline score", ""]
    lines += _table(
        ["pool", "hash", "ROC AUC", "average precision", "best F1", "at distance (bits)"],
        [
            [
                f"`{p.source}` {p.pool}",
                b.name,
                _f(b.auc),
                _f(b.average_precision),
                _f(b.best_f1),
                _int(b.best_distance),
            ]
            for p in audit.pools
            for b in p.baselines
        ],
    )
    lines += [
        "",
        _figure("roc.svg", "ROC curves"),
        "",
        _figure("pr.svg", "Precision-recall curves"),
        "",
    ]
    for p in audit.pools:
        if p.histogram:
            lines += [
                _figure(
                    f"histogram-{slug(p.source)}-{slug(p.pool)}.svg",
                    f"{p.source} {p.pool} histogram",
                ),
                "",
            ]
    lines += _synthetic_section(audit)
    return "\n".join(lines) + "\n"


def _synthetic_section(audit: Audit) -> list[str]:
    s = audit.synthetic
    if s is None:
        return ["## Synthetic positives", "", "Not computed.", ""]
    lines = [
        "## Synthetic positives",
        "",
        f"A seeded sample of {s.sample_per_source} images per source (seed {s.seed}); each image is "
        "compared with its own transformed copies.",
        "",
    ]
    lines += _table(
        [
            "transform",
            "kind",
            "in the near-duplicate set",
            "copies",
            "cosine: median (p05 to p95)",
            "min",
            "pHash p95 (bits)",
            "at or above near",
        ],
        [
            [
                r.transform,
                r.kind,
                "yes" if r.near_duplicate else "no",
                _int(r.n),
                _q(r.cosine),
                _f(r.cosine.minimum),
                _f(r.phash_p95, 1),
                _share(r.share_near),
            ]
            for r in s.by_transform
        ],
    )
    lines += ["", "The near-duplicate set per source (pHash p95 over its photometric copies):", ""]
    lines += _table(
        [
            "source",
            "copies",
            "cosine: median (p05 to p95)",
            "min",
            "pHash p95 (bits)",
            "at or above near",
        ],
        [
            [
                f"`{r.kind}`",
                _int(r.n),
                _q(r.cosine),
                _f(r.cosine.minimum),
                _f(r.phash_p95, 1),
                _share(r.share_near),
            ]
            for r in s.by_source
        ],
    )
    lines += ["", _figure("synthetic.svg", "Synthetic copies at or above near"), ""]
    return lines


# ----------------------------------------------------------------------- split leakage


def _crossing_cells(leak: SourceLeakage) -> list[str]:
    if not leak.has_splits:
        return [DASH] * 5
    return [
        _int(leak.groups_crossing_any),
        _int(leak.crossing.train_val),
        _int(leak.crossing.train_test),
        _int(leak.crossing.val_test),
        f"{leak.affected_images:,} of {leak.n_images:,} ({_pct(leak.affected_images, leak.n_images)})",
    ]


def _neighbour_cells(leak: SourceLeakage) -> list[str]:
    cells = []
    for split in ("val", "test"):
        row = next((n for n in leak.eval_neighbour if n.split == split), None)
        cells.append(
            DASH
            if row is None
            else f"{row.with_train_neighbour:,} of {row.images:,} ({_share(row.fraction)})"
        )
    return cells


def _reading(baseline: PermutationBaseline) -> str:
    n = baseline.n_permutations
    if baseline.p_upper <= 0.05:
        return f"more than random splits (p {_p_text(baseline.p_upper, n)})"
    if baseline.p_lower <= 0.05:
        return f"fewer than random splits (p {_p_text(baseline.p_lower, n)})"
    return "consistent with random splits"


def split_leakage(audit: Audit) -> str:
    lines = _header("M3 split leakage", audit)
    lines += [
        "> How common is it, in the official splits, for visually very similar images to sit on "
        "both sides of a split boundary? (protocol section 1)",
        "",
        "Groups come from the graph *within* each source (images are nodes, pairs at or above the "
        "level's cosine are edges). A group crosses a split when its members sit in two or more "
        "official splits; its images and annotations are then *affected*. `pcb-defect` has no "
        "official split.",
        "",
        "## Official splits",
        "",
    ]
    rows = []
    for level in audit.levels:
        for leak in level.leakage:
            primary = primary_level(audit, leak.source) == level.level
            rows.append(
                [
                    f"`{leak.source}`",
                    level.level + (" (primary)" if primary else ""),
                    _f(level.threshold, 4),
                    _int(leak.groups),
                    _int(leak.largest_group),
                    *_crossing_cells(leak),
                    _int(leak.affected_annotations) if leak.has_splits else DASH,
                    *_neighbour_cells(leak),
                ]
            )
    lines += _table(
        [
            "source",
            "level",
            "cosine",
            "groups (2+ images)",
            "largest group",
            "crossing groups",
            "train/val",
            "train/test",
            "val/test",
            "affected images",
            "affected annotations",
            "val images with a train neighbour",
            "test images with a train neighbour",
        ],
        rows,
    )
    family = _level(audit, "family")
    chained = family.chained_sources if family is not None else []
    lines += [
        "",
        "**Chaining rule** (protocol section 8): a source whose largest family-level group holds more "
        "than 25% of its images is flagged, and its near-level numbers become the primary ones. "
        + (
            "Flagged: " + ", ".join(f"`{s}`" for s in chained) + "."
            if chained
            else "No source is flagged, so the family level is primary everywhere."
        ),
        "",
        _figure("cross-split.svg", "Crossing groups against random splits"),
        "",
        "## Against random splits of the same sizes",
        "",
    ]
    rows = []
    for level in audit.levels:
        for source, baseline in sorted(level.permutation.items()):
            if baseline is None:
                continue
            rows.append(
                [
                    f"`{source}`",
                    level.level,
                    _int(baseline.observed),
                    f"{baseline.null_mean:.1f} ± {baseline.null_sd:.1f}",
                    _p(baseline.p_lower, baseline.n_permutations),
                    _p(baseline.p_upper, baseline.n_permutations),
                    _reading(baseline),
                ]
            )
    shuffles = next(
        (b.n_permutations for level in audit.levels for b in level.permutation.values() if b),
        None,
    )
    lines += [
        f"The split labels of each source are shuffled {_int(shuffles)} times (seed "
        f"{audit.run.seed}), keeping the split sizes; each shuffle is scored on the same groups.",
        "",
    ]
    lines += _table(
        [
            "source",
            "level",
            "crossing groups, official",
            "random splits: mean ± sd",
            "p (as few or fewer)",
            "p (as many or more)",
            "reading",
        ],
        rows,
    )
    lines += ["", "## A group-aware split with the official sizes (seed 0)", ""]
    rows = []
    for level in audit.levels:
        for source, rec in sorted(level.reconstructed.items()):
            if rec is None:
                continue
            rows.append(
                [
                    f"`{source}`",
                    level.level,
                    " / ".join(f"{k} {v:,}" for k, v in rec.ratios.items()),
                    " / ".join(f"{k} {v:,}" for k, v in rec.counts.items()),
                    _share(rec.max_ratio_error),
                    _int(rec.groups_crossing),
                    _q(rec.official_val_to_train),
                    _q(rec.val_to_train),
                    _q(rec.official_test_to_train),
                    _q(rec.test_to_train),
                ]
            )
    lines += [
        "Whole similarity groups are assigned to splits, largest first. The crossing count is "
        "measured on the result, not assumed. The last columns give each evaluation image's highest "
        "cosine to any training image (median, p05 to p95), official against group-aware.",
        "",
    ]
    lines += _table(
        [
            "source",
            "level",
            "official split",
            "group-aware split",
            "largest share error",
            "crossing groups after",
            "val to train, official",
            "val to train, group-aware",
            "test to train, official",
            "test to train, group-aware",
        ],
        rows,
    )
    lines += [
        "",
        "## Percolation",
        "",
        "Groups and the largest group as the threshold drops, per source.",
        "",
    ]
    sizes = {s.source: s.images for s in audit.run.sources}
    rows = [
        [
            f"`{r.source}`",
            _f(r.threshold, 4),
            _int(r.edges),
            _int(r.groups),
            _int(r.images_in_groups),
            f"{r.largest:,} ({_pct(r.largest, sizes.get(r.source))})",
            _int(r.groups_crossing_any),
            _int(r.affected_images),
        ]
        for r in sorted(audit.percolation, key=lambda r: (r.source, -r.threshold))
    ]
    lines += _table(
        [
            "source",
            "cosine",
            "pairs",
            "groups",
            "images in groups",
            "largest group",
            "crossing groups",
            "affected images",
        ],
        rows,
    )
    lines += ["", _figure("percolation.svg", "Largest group against threshold"), ""]
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------- source comparison


def _agreement_row(level: str, key: str, a: PartitionAgreement) -> list[str]:
    return [
        level,
        key,
        _int(a.n_images),
        _f(a.pair_precision),
        _f(a.pair_recall),
        _f(a.adjusted_rand),
        _f(a.homogeneity),
        _f(a.completeness),
        _f(a.multi_member_purity),
    ]


def _overlap_section(audit: Audit, source: str, title: str) -> list[str]:
    overlaps: list[KeyOverlap] = [
        o for level in audit.levels for o in level.key_overlap if o.source == source
    ]
    if not overlaps:
        return []
    lines = [f"## {title}", ""]
    rows = []
    for o in overlaps:
        rows.append(_agreement_row(o.level, o.key_group_name, o.vs_group))
        rows.append(_agreement_row(o.level, o.key_subgroup_name, o.vs_subgroup))
    lines += [
        "Pair precision: of the image pairs that share a similarity group, the share that also share "
        "the key. Pair recall: of the pairs that share the key, the share that also share a "
        "similarity group.",
        "",
    ]
    lines += _table(
        [
            "level",
            "key",
            "images",
            "pair precision",
            "pair recall",
            "adjusted Rand",
            "homogeneity",
            "completeness",
            "majority-key purity",
        ],
        rows,
    )
    lines += ["", "What the similar pairs (edges) are, in terms of the key:", ""]
    lines += _table(
        [
            "level",
            "edges",
            "same subgroup",
            "same group, other subgroup",
            "other group",
            "cross-split edges: same subgroup / same group / other group",
        ],
        [
            [
                o.level,
                _int(o.edge_mix.edges),
                _int(o.edge_mix.same_subgroup),
                _int(o.edge_mix.same_group_other_subgroup),
                _int(o.edge_mix.other_group),
                f"{o.edge_mix.cross_split_same_subgroup:,} / {o.edge_mix.cross_split_same_group_other_subgroup:,} / {o.edge_mix.cross_split_other_group:,}",
            ]
            for o in overlaps
        ],
    )
    with_splits = [o for o in overlaps if o.key_cross_split_images is not None]
    if with_splits:
        lines += [
            "",
            f"Images in a {with_splits[0].key_group_name} that spans splits (key) and images in a "
            "similarity group that spans splits (similarity):",
            "",
        ]
        lines += _table(
            [
                "level",
                "key spans splits",
                "similarity spans splits",
                "both",
                "key only",
                "similarity only",
                "neither",
                "crossing groups holding several keys",
            ],
            [
                [
                    o.level,
                    _int(o.key_cross_split_images),
                    _int(o.similarity_cross_split_images),
                    _int(o.both),
                    _int(o.only_key),
                    _int(o.only_similarity),
                    _int(o.neither),
                    _int(o.cross_split_groups_with_several_keys),
                ]
                for o in with_splits
            ],
        )
    lines += [""]
    return lines


def source_comparison(audit: Audit) -> str:
    lines = _header("M3 source comparison", audit)
    lines += _overlap_section(
        audit, "pcb-ind", "`pcb-ind`: production-batch key against DINOv2 groups"
    )
    lines += _overlap_section(
        audit, "pcb-defect", "`pcb-defect`: design family against DINOv2 groups"
    )
    lines += [
        "## `dspcbsd-plus`: is there a latent grouping? (protocol section 9)",
        "",
        "The source has no group key, so nothing below is ground truth.",
        "",
        "- (a) cohesion and (b) stability: tables below;",
        "- (c) agreement with pHash near-duplicates: "
        + _share(audit.hash_audit.phash_in_family_group.get("dspcbsd-plus"))
        + " of its pHash-candidate pairs fall inside one family-level group "
        "([similarity-summary.md](similarity-summary.md));",
        "- (d) transfer of the calibrated thresholds: table below;",
        "- (e) a second model: "
        + (
            f"`{audit.robustness.other_model}`"
            if audit.robustness
            else "not run in M3 (optional in the protocol)"
        )
        + ";",
        "- (f) a qualitative look: the seeded sample of groups in the local review pack "
        "(`openinspect dedup review`); it is not a verdict either.",
        "",
        "## Cohesion of the groups",
        "",
        "Connected components chain: a group can hold pairs far below its threshold. The weakest "
        "member pair of each group shows how much.",
        "",
    ]
    lines += _table(
        [
            "source",
            "level",
            "groups",
            "size: median (p05 to p95)",
            "max size",
            "weakest member pair: median (p05 to p95)",
            "mean member pair: median",
            "groups whose weakest pair is under review",
        ],
        [
            [
                f"`{c.source}`",
                c.level,
                _int(c.groups),
                _q(c.sizes, 1),
                _f(c.sizes.maximum if c.sizes else None, 0),
                _q(c.min_pairwise),
                _f(c.mean_pairwise.median if c.mean_pairwise else None),
                _share(c.share_below_review),
            ]
            for level in audit.levels
            for c in level.cohesion
        ],
    )
    lines += ["", "## Stability (family threshold ± 0.02)", ""]
    lines += _table(
        [
            "source",
            "thresholds",
            "groups (lower / higher)",
            "adjusted Rand",
            "pairs grouped at the lower still grouped at the higher",
        ],
        [
            [
                f"`{s.source}`",
                f"{_f(s.threshold_low, 4)} / {_f(s.threshold_high, 4)}",
                f"{s.groups_low:,} / {s.groups_high:,}",
                _f(s.adjusted_rand),
                _share(s.retained_pairs),
            ]
            for s in audit.stability
        ],
    )
    lines += ["", "## Transfer of the thresholds (protocol section 6)", ""]
    lines += _table(
        [
            "source",
            "has a key",
            "top-1 cosine: median (p05 to p95)",
            ">= review",
            ">= family",
            ">= near",
        ],
        [
            [
                f"`{r.source}`",
                "yes" if r.labelled else "no",
                _q(r.top1),
                _share(r.share_review),
                _share(r.share_family),
                _share(r.share_near),
            ]
            for r in audit.transfer
        ],
    )
    lines += [""]
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------- performance


def _gb(value: int | None) -> str:
    return DASH if value is None else f"{value / 1e9:.2f} GB"


def performance(audit: Audit) -> str:
    lines = _header("M3 performance", audit)
    p = audit.performance
    if p is None:
        lines += ["No performance record."]
        return "\n".join(lines) + "\n"
    rows = []
    for stage in p.stages:
        rate = f"{stage.images / stage.seconds:.1f}" if stage.images and stage.seconds else DASH
        rows.append(
            [
                stage.stage,
                f"{stage.seconds:,.1f}",
                _int(stage.images),
                rate,
                _gb(stage.peak_ram_bytes),
                stage.note or "",
            ]
        )
    lines += ["## Stages", ""]
    lines += _table(["stage", "seconds", "images", "images per second", "peak RAM", "note"], rows)
    lines += [
        "",
        "## Totals",
        "",
    ]
    lines += _table(
        ["item", "value"],
        [
            [
                "wall time of the stages above",
                f"{p.total_seconds:,.0f} s ({p.total_seconds / 60:.1f} min)",
            ],
            [
                "embedding throughput (cache build)",
                f"{_f(p.embed_images_per_second, 1)} images/s overall, {_f(p.embed_model_images_per_second, 1)} images/s in the model",
            ],
            [
                "embedding cache",
                f"{p.cache_files:,} files, {p.cache_bytes / 1e6:.1f} MB on disk ({p.cache_logical_bytes / 1e6:.1f} MB of vectors)",
            ],
            ["peak RAM", _gb(p.peak_ram_bytes)],
            ["processor", p.cpu or DASH],
            ["note", p.note or DASH],
        ],
    )
    lines += [
        "",
        "Artifacts (SHA-256):",
        "",
    ]
    lines += _table(
        ["file", "SHA-256"],
        [[f"`{name}`", f"`{digest}`"] for name, digest in sorted(audit.artifacts.items())],
    )
    lines += [""]
    return "\n".join(lines) + "\n"


# ------------------------------------------------------------------------------ write

RENDERERS: dict[str, Callable[[Audit], str]] = {
    "similarity-summary.md": similarity_summary,
    "threshold-calibration.md": threshold_calibration,
    "split-leakage.md": split_leakage,
    "source-comparison.md": source_comparison,
    "performance.md": performance,
}


def render_reports(audit: Audit) -> dict[str, str]:
    """Relative path -> text of every report file (Markdown and SVG)."""
    files = {name: render(audit) for name, render in RENDERERS.items()}
    files.update({f"figures/{name}": text for name, text in figures(audit).items()})
    return files


def write_reports(folder: Path, audit: Audit) -> list[Path]:
    """Write the reports; figures that are no longer produced are removed from ``figures/``."""
    files = render_reports(audit)
    written: list[Path] = []
    for name, text in sorted(files.items()):
        path = folder / name
        path.parent.mkdir(parents=True, exist_ok=True)
        temporary = path.with_name(f"{path.name}.{os.getpid()}.tmp")
        temporary.write_bytes(text.encode("utf-8"))
        os.replace(temporary, path)
        written.append(path)
    figures_dir = folder / "figures"
    if figures_dir.is_dir():
        for stale in figures_dir.glob("*.svg"):
            if f"figures/{stale.name}" not in files:
                stale.unlink()
    return written
