"""The M5 report, rendered from ``release.json`` alone (a pure function of the manifest)."""

from __future__ import annotations

import os
from collections.abc import Sequence
from pathlib import Path

from openinspect.release.config import SPLITS
from openinspect.release.groups import KINDS
from openinspect.release.manifest import ReleaseManifest, SchemeEntry
from openinspect.release.splits import EXCLUDED

DASH = "n/a"
REPORT = "release.md"
CATEGORIES = ("NEAR_DUPLICATE", "SAME_FAMILY_OR_SCENE", "REVIEW_REQUIRED")


def _int(value: int) -> str:
    return f"{value:,}"


def _pct(part: float, whole: float) -> str:
    return DASH if not whole else f"{100 * part / whole:.1f}%"


def _table(headers: Sequence[str], rows: Sequence[Sequence[str]]) -> list[str]:
    lines = ["| " + " | ".join(headers) + " |", "|" + "---|" * len(headers)]
    lines.extend("| " + " | ".join(row) + " |" for row in rows)
    return lines


def _validation(manifest: ReleaseManifest) -> str:
    record = manifest.m3_limitations.human_validation
    text = (
        f"**Human validation: {record.status}.** Reviewed pairs: {record.reviewed} / "
        f"{record.queued} (`{record.queue}`)."
    )
    return f"{text} {record.limitation}" if record.limitation else text


def _split_cells(entry: SchemeEntry, sources: Sequence[str]) -> list[list[str]]:
    names = [s for s in (*SPLITS, EXCLUDED) if s in entry.measure.images]
    rows = []
    for name in names:
        per_source = entry.measure.images[name]
        rows.append(
            [
                f"`{name}`",
                _int(sum(per_source.values())),
                *(_int(per_source.get(s, 0)) for s in sources),
                _int(sum(entry.measure.boxes.get(name, {}).values())),
            ]
        )
    return rows


def render(manifest: ReleaseManifest) -> str:
    commit = manifest.generated_by.code_commit
    code = (
        DASH
        if commit is None
        else f"`{commit[:12]}`"
        + (" with uncommitted changes" if manifest.generated_by.code_dirty else "")
    )
    sources = [s.source for s in manifest.sources]
    classes = manifest.taxonomy.benchmark_classes
    total = manifest.counts.images
    lines = [
        f"# Release {manifest.version}: assembly and canonical splits",
        "",
        f"Generated by `openinspect release build` from `manifests/releases/{manifest.version}/release.json` "
        f"(re-render with `openinspect release report`). Code: {code}; seed {manifest.seed}; "
        f"Pillow {manifest.generated_by.pillow}, libjpeg {manifest.generated_by.libjpeg or DASH}.",
        "",
        _validation(manifest),
        "",
        "A1 and B group items by the M3 visual similarity components (machine-detected potential "
        "leakage groups), so they inherit these limitations:",
        "",
        *(f"- {statement}" for statement in manifest.m3_limitations.statements),
        "",
        "## Summary",
        "",
        f"{_int(total)} images and {_int(manifest.counts.boxes)} boxes of "
        f"{len(classes)} classes ({', '.join(f'`{c}`' for c in classes)}) from {len(sources)} "
        f"sources; the canonical split stored with every item is `{manifest.canonical_split}`.",
        "",
    ]
    lines += _table(
        [
            "source",
            "licence",
            "version",
            "ingested images",
            "candidates",
            "released",
            "share",
            "boxes",
        ],
        [
            [
                f"`{s.source}`",
                s.licence,
                s.version or DASH,
                _int(s.images_ingested),
                _int(s.candidates),
                _int(s.released_images),
                f"{100 * s.share:.1f}%",
                _int(s.released_boxes),
            ]
            for s in manifest.sources
        ],
    )
    lines += [
        "",
        "Every source is CC BY 4.0 with attribution required; the attribution text and the "
        "change notice are in `release.json` (`sources[].attribution`). Crops are changes to the "
        "original images and must be indicated as such.",
        "",
        "## Classes",
        "",
    ]
    lines += _table(
        ["id", "class", *(f"`{s}`" for s in sources), "boxes", "images"],
        [
            [
                str(c.class_id),
                f"`{c.name}`",
                *(
                    ", ".join(
                        f"`{label}` ({status})"
                        for label, status in zip(
                            c.original_labels.get(s, []), c.statuses.get(s, []), strict=False
                        )
                    )
                    or "-"
                    for s in sources
                ),
                _int(c.released_boxes),
                _int(c.released_images),
            ]
            for c in manifest.taxonomy.classes
        ],
    )
    lines += ["", "## What was excluded, and why", ""]
    lines += [
        "Nothing is dropped silently: every image that is not released, and every crop anchor "
        "that gave no crop, is a row of `excluded.parquet`. Counts are images, except the "
        "`crop_*` reasons, which count anchor boxes.",
        "",
    ]
    lines += _table(
        ["source", "reason", "count"],
        [
            [f"`{s.source}`", f"`{reason}`", _int(n)]
            for s in manifest.sources
            for reason, n in s.exclusions.items()
        ],
    )
    crops = [s for s in manifest.sources if s.crop_policy is not None]
    if crops:
        lines += ["", "## Crop policy (decision D7, frozen in T32)", ""]
        for s in crops:
            policy = s.crop_policy
            assert policy is not None  # noqa: S101 - filtered above
            lines.append(
                f"- `{s.source}`: square crops of at least {policy.min_side_px} px in native "
                f"pixels around each benchmark box (the box fills at most "
                f"{100 * (1 - 2 * policy.margin):.0f}% of the side), saved as {policy.format.upper()}; "
                "a crop must not overlap an earlier crop of the same image, cut a box, or contain a "
                f"box of another class. {_int(s.released_images)} crops released."
            )
    lines += [
        "",
        "## Sample",
        "",
        f"A {manifest.sampling.method}. Share limit {manifest.sampling.max_source_share:.0%}; "
        "candidates and released items per source: "
        + ", ".join(
            f"`{s}` {_int(n)} to {_int(manifest.sampling.quotas.get(s, 0))}"
            for s, n in manifest.sampling.available.items()
        )
        + ".",
        "",
        "## Splits",
        "",
    ]
    for entry in manifest.splits:
        m = entry.measure
        lines += [
            f"### `{entry.name}` ({entry.kind.replace('_', ' ')})",
            "",
            f"{entry.method}. Target ratios {entry.ratios}; file `{entry.file}`.",
            "",
        ]
        lines += _table(
            ["split", "items", *(f"`{s}`" for s in sources), "boxes"], _split_cells(entry, sources)
        )
        lines += [
            "",
            "Measured after the split: constraints crossing a split boundary "
            + ", ".join(f"{kind} {_int(m.constraints_crossing.get(kind, 0))}" for kind in KINDS)
            + f" (total {_int(m.supplied_groups_crossing)}); M3 pairs whose items lie in two splits "
            + ", ".join(f"{c} {_int(m.pairs_crossing.get(c, 0))}" for c in CATEGORIES)
            + "; of them between train and test "
            + ", ".join(f"{c} {_int(m.pairs_train_test.get(c, 0))}" for c in CATEGORIES)
            + f"; at the primary level {_int(m.primary_pairs_crossing)}; files in two splits "
            f"{_int(m.sha256_crossing)}.",
            "",
        ]
    if manifest.notes:
        lines += ["## Notes on reading the splits", ""]
        lines += [f"- {note}" for note in manifest.notes]
        lines += [""]
    lines += ["## Invariants", ""]
    lines += _table(
        ["id", "rule", "status", "detail"],
        [[i.id, i.rule, f"**{i.status}**", i.detail] for i in manifest.invariants],
    )
    lines += ["", "## How to read the three regimes", ""]
    lines += [f"- {text}" for text in manifest.interpretation]
    lines += ["", "## Files", ""]
    lines += _table(["file", "SHA-256"], [[f"`{k}`", f"`{v}`"] for k, v in manifest.files.items()])
    lines += [""]
    lines += _table(
        ["split file", "SHA-256"], [[f"`{e.file}`", f"`{e.sha256}`"] for e in manifest.splits]
    )
    lines += [""]
    return "\n".join(lines) + "\n"


def write_report(folder: Path, manifest: ReleaseManifest) -> Path:
    folder.mkdir(parents=True, exist_ok=True)
    path = folder / REPORT
    temporary = path.with_name(f"{path.name}.{os.getpid()}.tmp")
    temporary.write_bytes(render(manifest).encode("utf-8"))
    os.replace(temporary, path)
    return path
