"""The ingest report: one JSON per source (tracked in git) and one Markdown table for all sources."""

from __future__ import annotations

import json
from collections.abc import Sequence
from pathlib import Path
from typing import Literal

from pydantic import Field

from openinspect.provenance.schema import Slug, StrictModel

Severity = Literal["info", "warning", "error"]
AdapterStatus = Literal["ok", "ok_with_warnings", "failed"]
GroupQuality = Literal["explicit", "derived", "weak", "none"]
SEVERITY_ORDER = {"error": 0, "warning": 1, "info": 2}


class Anomaly(StrictModel):
    code: str
    severity: Severity
    message: str
    count: int = Field(ge=1)
    examples: list[str] = Field(default_factory=list)


class ClassCount(StrictModel):
    label: str
    label_id: int | None = None
    count: int = Field(ge=0)


class SplitCount(StrictModel):
    split: str
    images: int = Field(ge=0)
    annotations: int = Field(ge=0)
    images_without_annotations: int = Field(ge=0)


class GroupingInfo(StrictModel):
    key: str | None  # what the key is, e.g. "batch = first 4 characters of the file name"
    quality: GroupQuality
    n_groups: int | None = None
    summary: str
    evidence: list[str] = Field(default_factory=list)


class ArchiveCheck(StrictModel):
    filename: str
    bytes: int
    size_ok: bool | None
    checksum_algo: str | None
    checksum_ok: bool | None
    sha256: str
    files_extracted: int
    zip_crc_ok: bool = True  # extraction reads every member and checks its CRC-32


class DecodeInfo(StrictModel):
    images: int
    decodable: int
    failed: int
    failures: list[str] = Field(default_factory=list)


class DuplicateInfo(StrictModel):
    groups: int
    redundant_files: int
    cross_split_groups: int


class Reconciliation(StrictModel):
    field: str
    manifest: str | None
    observed: str
    status: Literal["match", "mismatch", "new"]  # new = the manifest had no value (null)


class AdapterInfo(StrictModel):
    name: str
    version: int
    status: AdapterStatus
    canonical_format: str
    formats_present: list[str]


class LicenceTrace(StrictModel):
    """How the licence and the credit line stay traceable from the source manifest."""

    manifest: str  # repository-relative path of the manifest
    spdx: str | None
    licence_url: str | None
    attribution_in_manifest: bool
    evidence_files: int
    archive_says: list[str] = Field(default_factory=list)  # what the archive itself states


class SourceReport(StrictModel):
    schema_version: Literal[1] = 1
    slug: Slug
    dataset_name: str
    archive: ArchiveCheck
    adapter: AdapterInfo
    images: int = Field(ge=0)
    annotations: int = Field(ge=0)
    decode: DecodeInfo
    classes: list[ClassCount]
    splits: list[SplitCount]
    grouping: GroupingInfo
    exact_duplicates: DuplicateInfo
    anomalies: list[Anomaly]
    reconciliation: list[Reconciliation]
    licence: LicenceTrace
    digests: dict[str, str]
    notes: list[str] = Field(default_factory=list)


class CrossSource(StrictModel):
    """Exact duplicates between sources (same SHA-256 in two different sources)."""

    schema_version: Literal[1] = 1
    sources: list[str]
    images_per_source: dict[str, int]
    shared_sha256: int
    groups: list[list[str]] = Field(default_factory=list)  # each: "slug:source_item_id" entries


def write_json(path: Path, model: StrictModel) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    text = json.dumps(model.model_dump(mode="json"), indent=2, sort_keys=True, ensure_ascii=True)
    path.write_bytes((text + "\n").encode("utf-8"))


# ------------------------------------------------------------------------------ Markdown


def _n(value: int) -> str:
    return f"{value:,}"


def _classes_cell(report: SourceReport) -> str:
    parts = " · ".join(f"{c.label} {_n(c.count)}" for c in report.classes)
    return f"{len(report.classes)}: {parts}"


def _splits_cell(report: SourceReport) -> str:
    if not report.splits:
        return "none shipped"
    return " / ".join(f"{s.split} {_n(s.images)}" for s in report.splits)


def _grouping_cell(report: SourceReport) -> str:
    grouping = report.grouping
    return "none" if grouping.key is None else f"{grouping.key} ({grouping.quality})"


def _anomalies_cell(report: SourceReport) -> str:
    if not report.anomalies:
        return "none"
    ordered = sorted(report.anomalies, key=lambda a: (SEVERITY_ORDER[a.severity], a.code))
    return "; ".join(f"{a.code} ×{_n(a.count)}" for a in ordered)


def render_markdown(
    reports: Sequence[SourceReport],
    cross: CrossSource | None,
    *,
    title: str = "M2 ingest report",
) -> str:
    lines = [
        f"# {title}",
        "",
        "Generated by `openinspect ingest report` from `manifests/ingest/*/report.json`. Raw data stays "
        "outside the repository; the records behind these numbers are reproducible from the archives "
        "whose hashes are in the source manifests.",
        "",
        "| source | images | annotations | classes | original splits | identifiable grouping key "
        "| anomalies | adapter status |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for r in reports:
        lines.append(
            f"| `{r.slug}` | {_n(r.images)} | {_n(r.annotations)} | {_classes_cell(r)} "
            f"| {_splits_cell(r)} | {_grouping_cell(r)} | {_anomalies_cell(r)} "
            f"| {r.adapter.status} (canonical: {r.adapter.canonical_format}; "
            f"formats: {', '.join(r.adapter.formats_present)}) |"
        )
    if cross is not None:
        lines += [
            "",
            f"Cross-source exact duplicates (same SHA-256 in two sources): **{_n(cross.shared_sha256)}** "
            f"among {', '.join(f'{k} {_n(v)}' for k, v in cross.images_per_source.items())} images.",
        ]
    for r in reports:
        lines += ["", f"## `{r.slug}`", ""]
        lines.append(
            f"- archive `{r.archive.filename}`: {_n(r.archive.bytes)} bytes, size "
            f"{_ok(r.archive.size_ok)}, {r.archive.checksum_algo or 'no'} checksum "
            f"{_ok(r.archive.checksum_ok)}, SHA-256 `{r.archive.sha256}`, "
            f"{_n(r.archive.files_extracted)} files extracted (CRC-32 of every member checked)"
        )
        lines.append(
            f"- images decoded: {_n(r.decode.decodable)} of {_n(r.decode.images)}"
            + (f"; failures: {', '.join(r.decode.failures)}" if r.decode.failures else "")
        )
        lines.append(
            f"- exact duplicates inside the source: {_n(r.exact_duplicates.groups)} groups, "
            f"{_n(r.exact_duplicates.redundant_files)} redundant files, "
            f"{_n(r.exact_duplicates.cross_split_groups)} spanning splits"
        )
        lines.append(f"- grouping: {r.grouping.summary}")
        for item in r.grouping.evidence:
            lines.append(f"  - {item}")
        lines.append(
            f"- licence traceability: manifest `{r.licence.manifest}` ({r.licence.spdx}, "
            f"attribution text {'present' if r.licence.attribution_in_manifest else 'MISSING'}, "
            f"{r.licence.evidence_files} archived evidence files)"
            + (
                "; archive says: " + " | ".join(r.licence.archive_says)
                if r.licence.archive_says
                else ""
            )
        )
        if r.anomalies:
            lines += ["", "Anomalies:", ""]
            for a in sorted(r.anomalies, key=lambda a: (SEVERITY_ORDER[a.severity], a.code)):
                ex = f" (e.g. {', '.join(f'`{e}`' for e in a.examples)})" if a.examples else ""
                lines.append(f"- **{a.severity}** `{a.code}` ×{_n(a.count)}: {a.message}{ex}")
        if r.reconciliation:
            lines += ["", "Manifest reconciliation (ingest gate G7):", ""]
            lines += ["| field | manifest | observed | status |", "|---|---|---|---|"]
            for row in r.reconciliation:
                lines.append(
                    f"| {row.field} | {row.manifest if row.manifest is not None else '—'} "
                    f"| {row.observed} | {row.status} |"
                )
        for note in r.notes:
            lines.append(f"\n> {note}")
    return "\n".join(lines) + "\n"


def _ok(value: bool | None) -> str:
    return "n/a" if value is None else ("matches" if value else "DIFFERS")
