"""The M5.5 reports, rendered from ``artifacts/m5_5/readiness.json`` (``openinspect readiness report``)."""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from pathlib import Path

from openinspect.files import replace_bytes
from openinspect.readiness.models import Readiness

FOLDER = "reports/m5_5"
SPLITS = ("train", "val", "test", "excluded")


def _n(value: int) -> str:
    return f"{value:,}"


def _p(value: float | None) -> str:
    return "—" if value is None else f"{100 * value:.1f}%"


def _f(value: float | None, digits: int = 3) -> str:
    return "—" if value is None else f"{value:.{digits}f}"


def _header(r: Readiness, title: str) -> list[str]:
    v = r.human_validation
    commit = (r.provenance.code_commit or "unknown")[:12]
    statement = (
        f"**Human validation: {v['status']}.** Reviewed pairs: {v['reviewed']} / {v['queued']} "
        f"(`{v['queue']}`)."
    )
    if v.get("limitation"):
        statement += f" {v['limitation']}"
    return [
        f"# {title}",
        "",
        f"Generated by `{r.provenance.command}` from `artifacts/m5_5/readiness.json` (re-render with "
        f"`openinspect readiness report`). Release {r.provenance.release}; code `{commit}`"
        f"{' (uncommitted changes)' if r.provenance.code_dirty else ''}; design seeds "
        f"{', '.join(str(s) for s in r.provenance.design_seeds)}; split seed {r.provenance.split_seed}.",
        "",
        statement,
        "",
        "Vocabulary: a *visual similarity component* is a machine-detected potential leakage group "
        "(an embedding-defined component), not proof that two images show one physical board.",
        "",
    ]


def _table(header: Sequence[str], rows: Sequence[Sequence[object]]) -> list[str]:
    lines = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    lines += ["| " + " | ".join(str(c) for c in row) + " |" for row in rows]
    return lines


def _split_rows(
    items: Mapping[str, Mapping[str, int]], sources: Sequence[str]
) -> list[list[object]]:
    rows: list[list[object]] = []
    for split in SPLITS:
        if split in items:
            counts = items[split]
            rows.append(
                [f"`{split}`", _n(sum(counts.values())), *(_n(counts.get(s, 0)) for s in sources)]
            )
    return rows


def _sources(r: Readiness) -> list[str]:
    return sorted(r.negatives.available)


# ------------------------------------------------------------------------------ reports


def training_readiness(r: Readiness) -> str:
    lines = _header(r, "M5.5: training readiness")
    lines += [
        "> If two EVREN YOLO runs produce different scores, can we explain what experimental factor caused that difference?",
        "",
        "## Verdict",
        "",
        f"**{r.verdict}**",
        "",
        r.verdict_rule,
        "",
        f"Blockers: {'none' if not r.blockers else ''}",
    ]
    lines += [f"- {b}" for b in r.blockers]
    lines += ["", "Explicit limitations:", ""]
    lines += [f"{k}. {text}" for k, text in enumerate(r.limitations, start=1)]
    lines += ["", "## The twelve questions", ""]
    for a in r.answers:
        lines += [f"**{a.number}. {a.question}**", "", a.answer, ""]
    lines += [
        "## Where the evidence is",
        "",
        "| report | content |",
        "|---|---|",
        "| [controlled-design.md](controlled-design.md) | the A0/A1 estimand, the paired C0/C1 design, B-strict and B-natural |",
        "| [representation-sensitivity.md](representation-sensitivity.md) | DINOv2-small against DINOv2-base on the release |",
        "| [pcb-defect-component.md](pcb-defect-component.md) | why one PCB-Defect group holds most of its crops |",
        "| [release-label-quality.md](release-label-quality.md) | M4 findings in the release, the negative policy, pHash-only pairs |",
        "| [source-probe.md](source-probe.md) | how predictable the source of an image is |",
        "| [export-validation.md](export-validation.md) | every package read by two independent parsers |",
        "| [m7-plan.md](m7-plan.md) | the training matrix, not executed |",
        "| [../m6/evren-smoke-test.md](../m6/evren-smoke-test.md) | the EVREN import smoke test |",
        "",
        "## Reproducibility",
        "",
        f"The committed M5 splits re-derive from the committed inputs: group keys "
        f"{'match' if r.reproduction.group_keys_match else 'DIFFER'}, schemes "
        + ", ".join(
            f"{k} {'match' if v else 'DIFFER'}" for k, v in r.reproduction.schemes_match.items()
        )
        + f"; the DINOv2-small components recomputed from the cache "
        f"{'match' if r.reproduction.small_components_match_m3 else 'differ from'} the M3 table. "
        "`openinspect readiness check` re-derives the designs, the held-out folds, the label "
        "intersection, the probe and the base-built A1 from committed files in CI.",
        "",
        *_table(
            ["model", "revision", "weights SHA-256", "family", "near"],
            [
                [
                    f"`{m.model_id}`",
                    f"`{m.revision[:12]}`",
                    f"`{m.weights_sha256[:16]}...`",
                    _f(r.provenance.thresholds[m.name]["family"], 4),
                    _f(r.provenance.thresholds[m.name]["near"], 4),
                ]
                for m in r.provenance.models
            ],
        ),
        "",
        "Inputs (not changed by M5.5):",
        "",
        *_table(
            ["file", "SHA-256"], [[f"`{k}`", f"`{v}`"] for k, v in r.provenance.inputs.items()]
        ),
        "",
        "Outputs:",
        "",
        *_table(
            ["file", "SHA-256"], [[f"`{k}`", f"`{v}`"] for k, v in r.provenance.outputs.items()]
        ),
        "",
    ]
    return "\n".join(lines)


def controlled_design(r: Readiness) -> str:
    sources = _sources(r)
    e = r.estimand
    lines = _header(r, "M5.5: the A0/A1 estimand and the controlled designs")
    lines += [
        "## Why A0 - A1 is not a pure leakage effect",
        "",
        *_table(
            ["", "test items", *(f"`{s}`" for s in sources)],
            [
                ["A0 test", _n(sum(e.a0_test.values())), *(_n(e.a0_test[s]) for s in sources)],
                ["A1 test", _n(sum(e.a1_test.values())), *(_n(e.a1_test[s]) for s in sources)],
            ],
        ),
        "",
        f"The two test sets share {e.test_overlap} items; A0 trains on {e.a0_train_holds_a1_test} of A1's test items.",
        "",
        *(f"- {line}" for line in e.reading),
        "",
        "## The paired common-evaluation design (C0 / C1)",
        "",
        "**What changes between conditions?**",
        "",
        *(f"- {c}" for c in r.designs[0].changes),
        "",
        "**What remains constant?**",
        "",
        *(f"- {c}" for c in r.designs[0].constant),
        "",
        "The test set has two parts. *Probes* are test items whose group-mates C0 trains on; "
        "*controls* are whole groups that neither condition trains on. C0 - C1 on the probes "
        "estimates the effect of training on group-mates of a test item; on the controls it "
        "should be close to zero, which makes them a negative control for the swap. Probes and "
        "controls are different kinds of items (probes sit in groups, controls are mostly "
        "singletons): each is compared between C0 and C1, never with the other.",
        "",
    ]
    params = r.designs[0].params
    lines += [
        "Parameters (every design): "
        + ", ".join(f"{k} {v}" for k, v in params.items())
        + ". Groups larger than `max_group` stay whole in training.",
        "",
        "In the condition tables, *M3 pairs train-test* counts M3 candidate pairs, by machine "
        "category, with one image in train and one in test. REVIEW_REQUIRED pairs are pHash-only "
        "(the M3 review and family levels coincide), and a SAME_FAMILY_OR_SCENE pair of a source "
        "whose primary level is near lies below that level; neither is a constraint, so C1 may "
        "hold them. The primary-level pairs are counted in the column before.",
        "",
    ]
    for d in r.designs:
        by = {c.name: c for c in d.conditions}
        lines += [
            f"### Design {d.seed}",
            "",
            "Roles: "
            + ", ".join(f"{k} {_n(v)}" for k, v in d.roles.items())
            + f" (file `{d.roles_file}`).",
            "",
            *_table(
                ["test part", "items", *(f"`{s}`" for s in sources)],
                [
                    [
                        "probes (exposed in C0)",
                        _n(sum(d.probes.values())),
                        *(_n(d.probes[s]) for s in sources),
                    ],
                    [
                        "controls",
                        _n(sum(d.controls.values())),
                        *(_n(d.controls[s]) for s in sources),
                    ],
                ],
            ),
            "",
            "How each probe is linked to its mates (the strongest direct link): "
            + ", ".join(f"{k} {_n(v)}" for k, v in d.probe_links.items())
            + ". *Similar pair* means an M3 pair at the source's primary level; *same metadata "
            "group* means the same production batch or design family without such a pair.",
            "",
            *_table(
                ["split", "items", *(f"`{s}`" for s in sources)],
                _split_rows(by["C0"].items, sources),
            ),
            "",
            "(C0; C1 has the same counts per split and source: "
            + (
                "yes"
                if d.train_items_equal_by_source and by["C0"].items == by["C1"].items
                else "NO"
            )
            + ".)",
            "",
            *_table(
                [
                    "condition",
                    "file",
                    "exposed test items",
                    "constraint groups crossing",
                    "primary-level pairs crossing",
                    "M3 pairs train-test",
                ],
                [
                    [
                        c.name,
                        f"`{c.file}`",
                        _n(c.exposed_test_items),
                        ", ".join(
                            f"{k} {v}" for k, v in c.measure.constraints_crossing.items() if v
                        )
                        or "0",
                        _n(c.measure.primary_pairs_crossing),
                        ", ".join(f"{k} {v}" for k, v in c.measure.pairs_train_test.items()) or "0",
                    ]
                    for c in d.conditions
                ],
            ),
            "",
            "Training boxes per class, C0 minus C1: "
            + ", ".join(f"{k} {v:+d}" for k, v in d.train_box_difference.items())
            + "; replacement matches: "
            + ", ".join(f"{k} {v}" for k, v in d.replacements.items())
            + " (profile = the same boxes per class).",
            "",
            "Shortfalls against the targets: "
            + "; ".join(
                f"`{s}` " + ", ".join(f"{k} {v}" for k, v in values.items() if v)
                for s, values in d.shortfalls.items()
                if any(values.values())
            )
            + ".",
            "",
        ]
    lines += [
        "## Two source-held-out regimes",
        "",
        "- **B-strict** (the M5 split `B-<source>`): the held-out source is the test set, and training items that share a constraint *directly* with a held-out item are excluded. It asks how a model generalizes when both source identity and the known machine-similarity overlap are removed.",
        "- **B-natural** (new): the held-out source is the test set and every other item is available for training and validation (group-aware), including items a machine similarity component links to the held-out source. It asks how a model generalizes to an unseen acquisition source under naturally occurring cross-source similarity.",
        "",
        "The historical name `B` stays the file name of B-strict.",
        "",
        *_table(
            [
                "fold",
                "regime",
                "file",
                "train",
                "val",
                "test",
                "excluded",
                "pure",
                "constraints crossing",
                "primary pairs crossing",
                "training items linked to test",
            ],
            [
                [
                    f"`{h.fold}`",
                    h.regime,
                    f"`{h.file}`",
                    _n(sum(h.items.get("train", {}).values())),
                    _n(sum(h.items.get("val", {}).values())),
                    _n(sum(h.items.get("test", {}).values())),
                    _n(h.excluded),
                    "yes" if h.pure else "NO",
                    _n(h.measure.supplied_groups_crossing),
                    _n(h.measure.primary_pairs_crossing),
                    _n(h.linked_training_items),
                ]
                for h in r.held_out
            ],
        ),
        "",
        "*Training items linked to test*: training or validation items whose A1 constraint group "
        "(the transitive union of all constraints) also holds a test item. B-strict excludes only "
        "the items that share a single constraint with a held-out item, so transitive links can "
        "remain; B-natural keeps every link.",
        "",
    ]
    return "\n".join(lines)


def representation(r: Readiness) -> str:
    x = r.representation
    lines = _header(r, "M5.5: representation sensitivity of the release splits")
    lines += [
        "> Would choosing DINOv2-base instead of DINOv2-small materially change the actual training and evaluation population?",
        "",
        f"**Answer: {'yes' if x.material else 'no'}.** "
        + ("; ".join(x.material_reasons) if x.material_reasons else "No criterion was met.")
        + ". Criteria fixed before the computation: at least 10% of the items change split, a "
        "source gains or loses a split, or a source's share of the test set moves by 5 points or more.",
        "",
        "Both models are calibrated by the same frozen M3 rule; each source keeps the primary level "
        "its own chaining rule gives it. A1-base is A1's algorithm, seed and targets with the base "
        "components in place of the small ones (metadata keys, identical files and crop parents unchanged).",
        "",
        *_table(
            ["", "family", "near", *(f"primary `{s}`" for s in sorted(x.small_primary))],
            [
                [
                    f"`{x.small_model}`",
                    _f(x.small_thresholds["family"], 4),
                    _f(x.small_thresholds["near"], 4),
                    *(x.small_primary[s] for s in sorted(x.small_primary)),
                ],
                [
                    f"`{x.base_model}`",
                    _f(x.base_thresholds["family"], 4),
                    _f(x.base_thresholds["near"], 4),
                    *(x.base_primary[s] for s in sorted(x.base_primary)),
                ],
            ],
        ),
        "",
        "## Membership on the released items",
        "",
        *_table(
            [
                "source",
                "items",
                "in a component (small / base)",
                "components",
                "largest component",
                "largest constraint group",
                "adjusted Rand",
                "pair precision",
                "pair recall",
            ],
            [
                [
                    f"`{m.source}`",
                    _n(m.items),
                    f"{_n(m.in_component_small)} / {_n(m.in_component_base)}",
                    f"{_n(m.components_small)} / {_n(m.components_base)}",
                    f"{_n(m.largest_small)} / {_n(m.largest_base)}",
                    f"{_n(m.largest_group_small)} / {_n(m.largest_group_base)}",
                    _f(m.agreement.adjusted_rand),
                    _f(m.agreement.pair_precision),
                    _f(m.agreement.pair_recall),
                ]
                for m in x.membership
            ],
        ),
        "",
        "Agreement compares the base components (predicted) with the small ones (reference) on the "
        "items that either model puts in a component: pair precision is the share of base-grouped "
        "pairs that small also groups, pair recall the reverse.",
        "",
        "## Consequences for the splits",
        "",
        *_table(
            [
                "source",
                "items",
                "change split",
                "A1 train / val / test",
                "A1-base train / val / test",
            ],
            [
                [
                    f"`{c.source}`",
                    _n(c.items),
                    f"{_n(c.changed)} ({_p(c.changed / c.items)})",
                    " / ".join(_n(c.a1[s]) for s in ("train", "val", "test")),
                    " / ".join(_n(c.a1_base[s]) for s in ("train", "val", "test")),
                ]
                for c in x.split_changes
            ],
        ),
        "",
        f"- {_n(x.changed_items)} of the items ({_p(x.changed_share)}) would be in another split.",
        f"- The committed A1 cuts {sum(x.a1_cuts_base.values())} base constraint groups ("
        + ", ".join(f"{k} {v}" for k, v in x.a1_cuts_base.items() if v)
        + f") and {_n(x.a1_pairs_crossing_base)} base similar pairs cross it.",
        f"- A1-base would cut {sum(x.a1_base_cuts_small.values())} small constraint groups ("
        + ", ".join(f"{k} {v}" for k, v in x.a1_base_cuts_small.items() if v)
        + f"), holding {_n(x.admissibility_changed_items)} items whose A1 split is no longer forced, "
        f"and leave {_n(x.a1_base_primary_pairs_crossing)} small primary-level pairs across its splits "
        "(between train and test: "
        + ", ".join(f"{k} {v}" for k, v in x.a1_base_pairs_train_test.items())
        + f"); {_n(x.a1_base_pairs_crossing_base)} base pairs cross it.",
        "- Test-set share per source, A1-base minus A1: "
        + ", ".join(f"`{s}` {100 * v:+.1f} points" for s, v in x.test_share_shift.items())
        + ".",
        "- Splits present per source: "
        + "; ".join(
            f"A1 `{s}` {'/'.join(x.split_presence['A1'][s])} against A1-base {'/'.join(x.split_presence['A1-base'][s])}"
            for s in sorted(x.split_presence["A1"])
        )
        + ".",
        "- DINOv2-base similar pairs with one image in train and one in test of the C designs: "
        + ", ".join(f"{k} {_n(v)}" for k, v in x.designs_base_pairs_train_test.items())
        + ".",
        "",
        *_table(
            ["B-strict fold", "excluded under small", "excluded under base"],
            [[f"`{h.fold}`", _n(h.excluded_small), _n(h.excluded_base)] for h in x.held_out],
        ),
        "",
        "## Reading",
        "",
        "A1 and B are defined by the DINOv2-small components and are not replaced: the M3 protocol "
        "made small the primary representation before any result, and base misses more of the "
        "synthetic near-duplicates (M3). But the populations those splits produce depend on that "
        "choice, so every result of A1, B and the C designs is a result *under the DINOv2-small "
        "grouping*, and the M7 report has to say so. The C designs use the same grouping: their "
        "contrast is the effect of training on group-mates as the DINOv2-small components, the "
        "metadata keys and the crop parents define them, and the probes and controls are recorded "
        "item by item. The DINOv2-base pairs between their train and test sets (above) show how "
        "much of C1's separation also holds under the other representation.",
        "",
    ]
    return "\n".join(lines)


def giant(r: Readiness) -> str:
    g = r.giant
    lines = _header(r, "M5.5: the PCB-Defect giant component")
    lines += [
        f"One A1 constraint group holds **{_n(g.largest_group)} of the {_n(g.items)}** released "
        f"`{g.source}` crops. Verdict: **{g.verdict}**.",
        "",
        *(f"- {c}" for c in g.causes),
        "",
        "## Which constraints build it",
        "",
        *_table(
            ["constraints joined", "groups of two or more", "largest group", "singletons"],
            [
                [", ".join(d.kinds), _n(d.groups), _n(d.largest), _n(d.singletons)]
                for d in g.decomposition
            ],
        ),
        "",
        "## The scan-level similarity graph",
        "",
        "M3 computed the components on whole scans resized to 224x224; every crop inherits its scan's component.",
        "",
        *_table(
            [
                "model",
                "threshold",
                "scans",
                "edges",
                "components",
                "largest",
                "design families in it",
                "edge min",
                "all-pair min",
                "all-pair mean",
                "chaining gap",
                "diameter",
                "mean path",
            ],
            [
                [
                    f"`{s.model}`",
                    _f(s.threshold, 4),
                    _n(s.scans),
                    _n(s.edges),
                    _n(s.components),
                    _n(s.largest),
                    f"{s.largest_families} of {s.families}",
                    _f(s.edge_min),
                    _f(s.all_pairs_min),
                    _f(s.all_pairs_mean),
                    _f(s.chaining_gap),
                    "—" if s.diameter is None else str(s.diameter),
                    _f(s.mean_path, 2),
                ]
                for s in g.scan_graphs
            ],
        ),
        "",
        "## Threshold sensitivity (largest scan component, share of scans)",
        "",
    ]
    models = sorted({p.model for p in g.sweep})
    thresholds = sorted({p.threshold for p in g.sweep})
    table = {(p.model, p.threshold): p for p in g.sweep}
    lines += _table(
        ["threshold", *(f"`{m}`" for m in models)],
        [
            [
                _f(t, 3),
                *(_p(table[(m, t)].largest_share) if (m, t) in table else "—" for m in models),
            ]
            for t in thresholds
        ],
    )
    lines += [
        "",
        "## If the components were computed on the crops",
        "",
        *_table(
            [
                "model",
                "threshold",
                "crops",
                "largest crop component",
                "largest group with crop parents, families and identical files",
                "edges across scans",
                "edges across families",
            ],
            [
                [
                    f"`{c.model}`",
                    _f(c.threshold, 4),
                    _n(c.crops),
                    _n(c.largest_component),
                    _n(c.largest_group_with_constraints),
                    _n(c.cross_scan_edges),
                    _n(c.cross_family_edges),
                ]
                for c in g.crop_graphs
            ],
        ),
        "",
        "## Rules of the verdict (fixed before the diagnostics ran)",
        "",
        *(f"- {rule}" for rule in g.rules),
        "",
        "## Consequence",
        "",
        "The group is not broken by hand to obtain nicer split ratios. Under the A1 grouping rule "
        "PCB-Defect cannot take part in every split: A1 holds it in train and validation only, the "
        "C designs hold it in train and test (one exposure group, one control group) and in no "
        "validation set, and it is tested as a whole only when it is held out (B).",
        "",
    ]
    return "\n".join(lines)


def label_quality(r: Readiness) -> str:
    x = r.labels
    lines = _header(r, "M5.5: label findings in the release, negatives, pHash-only pairs")
    lines += [
        f"## M4 findings against release {r.provenance.release}",
        "",
        f"All {_n(x.findings)} rows of `artifacts/m4/review-required.csv` were placed against the released items "
        f"(`{r.labels_file}`). No label was corrected.",
        "",
        *_table(
            ["category", "findings", "released items", "released boxes"],
            [
                [
                    c,
                    _n(x.by_category[c]),
                    _n(x.released_items_affected[c]),
                    _n(x.released_boxes_affected[c]),
                ]
                for c in x.by_category
            ],
        ),
        "",
        *_table(
            ["signal", *x.by_category],
            [[f"`{s}`", *(_n(v.get(c, 0)) for c in x.by_category)] for s, v in x.by_signal.items()],
        ),
        "",
        *_table(
            ["source", *x.by_category],
            [[f"`{s}`", *(_n(v.get(c, 0)) for c in x.by_category)] for s, v in x.by_source.items()],
        ),
        "",
        "Rules: FATAL = a released box with non-finite, inverted, zero-area or out-of-image "
        "geometry (it would be excluded by a documented rule; there is none); TRAINING_RELEVANT = "
        "a released box thinner than two pixels, a box drawn twice, a format disagreement, or a "
        "near-duplicate pair of released images with different labels; LIMITATION_ONLY = a size or "
        "shape outlier, an ambiguous mapping, or a label conflict whose counterpart is not "
        "released; NOT_IN_RELEASE = the flagged box or image is not released.",
        "",
        "Released label-conflict pairs whose two items lie in different splits: "
        + ", ".join(f"{k} {v}" for k, v in x.pairs_across_splits.items())
        + ".",
        "",
        "## Negative policy",
        "",
        *_table(
            ["source", "images without a box", "released"],
            [[f"`{s}`", _n(n), "0"] for s, n in r.negatives.available.items()],
        ),
        "",
        f"Policy: {r.negatives.policy}; reason recorded as `{r.negatives.excluded_reason}`. "
        f"The same policy applies in every regime: {'yes' if r.negatives.same_in_every_regime else 'no'}.",
        "",
        "Not tested because of it:",
        "",
        *(f"- {u}" for u in r.negatives.untested),
        "",
        "## pHash-only candidate pairs (P2)",
        "",
        f"{_n(r.phash_only.pairs)} M3 pairs are in review only because of their pHash distance "
        f"(below the review cosine) and have both images released: {_n(r.phash_only.same_source)} "
        f"inside a source, {_n(r.phash_only.cross_source)} across sources (`{r.phash_only.file}`). "
        "pHash distances: "
        + ", ".join(f"{k} bits {v}" for k, v in r.phash_only.phash_distance.items())
        + "; cosine DINOv2-small "
        + ", ".join(f"{k} {_f(v)}" for k, v in r.phash_only.cosine_small.items())
        + "; DINOv2-base "
        + ", ".join(f"{k} {_f(v)}" for k, v in r.phash_only.cosine_base.items())
        + ".",
        "",
        *_table(
            ["regime", "train-test", "train-val", "val-test", "same split", "not both assigned"],
            [
                [
                    f"`{x.regime}`",
                    _n(x.train_test),
                    _n(x.train_val),
                    _n(x.val_test),
                    _n(x.same_split),
                    _n(x.not_both_assigned),
                ]
                for x in r.phash_only.relations
            ],
        ),
        "",
        "They are not constraints (the M3 protocol defines no pHash similarity level) and do not "
        "block training; they stay visible for a publication-level follow-up.",
        "",
    ]
    return "\n".join(lines)


def source_probe(r: Readiness) -> str:
    p = r.probe
    lines = _header(r, "M5.5: source identity probe")
    lines += [
        "> Does the benchmark contain obvious source signatures?",
        "",
        p.reading,
        "",
        f"{_n(p.items)} released items: "
        + ", ".join(f"`{s}` {_n(n)}" for s, n in p.sources.items())
        + f"; feature table `{r.probe_features_file}`.",
        "",
        *_table(
            ["feature set", "features"],
            [[k, ", ".join(f"`{f}`" for f in v)] for k, v in p.features.items()],
        ),
        "",
        *_table(
            [
                "features",
                "model",
                "folds",
                "accuracy",
                "balanced accuracy",
                *(f"recall `{s}`" for s in p.sources),
            ],
            [
                [
                    s.features,
                    s.model,
                    s.folds,
                    _p(s.accuracy),
                    _p(s.balanced_accuracy),
                    *(_p(s.recall[k]) for k in p.sources),
                ]
                for s in p.scores
            ],
        ),
        "",
        "Five folds; *stratified* deals the items of each source to the folds in a seeded order, "
        "*group-aware* keeps every A1 constraint group in one fold. Logistic regression (multinomial, "
        "standardized features, L2) and a depth-three decision tree (Gini), both implemented in NumPy.",
        "",
        "## The depth-three trees fitted on all items",
        "",
    ]
    for name in ("metadata", "boxes+pixels"):
        lines += [f"`{name}`:", "", "```", *p.trees[name], "```", ""]
    lines += [
        "## Reading",
        "",
        "Source identity is close to trivially predictable. That does not invalidate the "
        "source-held-out regimes; it means B measures a large source and domain shift (image size "
        "and format, colour and box statistics all change with the source), not only a subtle "
        "generalization gap, and a B score must not be read as a leakage effect.",
        "",
    ]
    return "\n".join(lines)


def export_validation(r: Readiness) -> str:
    lines = _header(r, "M5.5: independent validation of the YOLO packages")
    lines += [
        "Every package of the M7 plan was built from the committed release and split files and read "
        "back by two parsers that share no code with the exporter.",
        "",
        "Independence:",
        "",
        *(f"- {x}" for x in r.export.independence),
        "",
        *_table(
            [
                "scheme",
                "package",
                "MB",
                "images train / val / test",
                "boxes (archive = expected)",
                "in-repo parser",
                "Ultralytics",
            ],
            [
                [
                    f"`{p.scheme}`",
                    f"`{p.package}`",
                    f"{p.bytes / 1e6:.0f}",
                    " / ".join(_n(p.items.get(s, 0)) for s in ("train", "val", "test")),
                    "yes" if p.boxes == p.expected_boxes else "NO",
                    f"{'PASS' if p.internal_ok else 'FAIL'} ({_n(p.internal_rows)} rows)",
                    "not run"
                    if p.ultralytics is None
                    else f"{'PASS' if p.ultralytics.ok else 'FAIL'} {p.ultralytics.version} ({_n(p.ultralytics.totals.get('boxes', 0))} boxes, {p.ultralytics.totals.get('corrupt', 0)} corrupt, {p.ultralytics.totals.get('missing_labels', 0)} missing)",
                ]
                for p in r.export.packages
            ],
        ),
        "",
        "Checked by the in-repository parser: every image decodes and has a label file, every label "
        "file has an image, every row has five finite fields, the class id is an integer of the "
        "four classes, the centre and size lie in [0, 1], width and height are positive, the box "
        "rebuilt from them leaves the image by at most half a pixel (the box rule of the ingest "
        "contract), and every class occurs. Ultralytics ran `check_det_dataset` on `data.yaml` and "
        "`verify_image_label` on every pair.",
        "",
    ]
    overhangs = [p for p in r.export.packages if p.internal_overhangs]
    if overhangs:
        lines += [
            "Boxes that leave the image by less than half a pixel (they pass, and are written as the "
            "release holds them):",
            "",
            *(
                f"- `{p.scheme}`: {_n(p.internal_overhangs)} boxes, largest overhang "
                f"{p.internal_max_overhang_px:.4f} px"
                for p in overhangs
            ),
            "",
        ]
    problems = [
        p
        for p in r.export.packages
        if p.internal_problems or (p.ultralytics and p.ultralytics.messages)
    ]
    if problems:
        lines += ["Problems:", ""]
        for p in problems:
            lines += [
                f"- `{p.scheme}`: " + ", ".join(f"{k} {v}" for k, v in p.internal_problems.items())
            ]
            lines += [f"  - {m}" for m in (p.ultralytics.messages if p.ultralytics else [])]
        lines.append("")
    else:
        lines += ["No problem was found in any package.", ""]
    return "\n".join(lines)


def m7_plan(r: Readiness) -> str:
    plan = r.plan
    lines = _header(r, "M7 plan: controlled YOLO11n experiments (not executed)")
    lines += [
        f"**{plan.not_executed}**",
        "",
        f"Model: {plan.model}. The configuration below is the same for every run.",
        "",
        *_table(["setting", "value"], [[f"`{k}`", v] for k, v in plan.config.items()]),
        "",
        "## Runs",
        "",
        *_table(
            ["run", "regime", "split file", "package", "training seed", "purpose"],
            [
                [
                    f"`{x.run_id}`",
                    x.regime,
                    f"`{x.split_file}`",
                    f"`{x.package}`",
                    x.training_seed,
                    x.purpose,
                ]
                for x in plan.runs
            ],
        ),
        "",
        f"{len(plan.runs)} runs. Every package is checked again after its EVREN import against its "
        "split file (the M6 procedure), with Auto Split off.",
        "",
        "## Metrics",
        "",
        *(f"- {m}" for m in plan.metrics),
        "",
        "## Analysis",
        "",
        *(f"- {a}" for a in plan.analysis),
        "",
    ]
    return "\n".join(lines)


RENDERERS = {
    "TRAINING_READINESS.md": training_readiness,
    "controlled-design.md": controlled_design,
    "representation-sensitivity.md": representation,
    "pcb-defect-component.md": giant,
    "release-label-quality.md": label_quality,
    "source-probe.md": source_probe,
    "export-validation.md": export_validation,
    "m7-plan.md": m7_plan,
}


def render_all(readiness: Readiness) -> dict[str, str]:
    return {f"{FOLDER}/{name}": render(readiness) for name, render in RENDERERS.items()}


def write_reports(root: Path, readiness: Readiness) -> list[Path]:
    written: list[Path] = []
    for path, text in render_all(readiness).items():
        replace_bytes(root / path, text.encode("utf-8"))
        written.append(root / path)
    return written
